service: geoip
frameworkVersion: ">=1.34.0 <2.0.0"

provider:
  name: aws
  runtime: python3.6

functions:
  hello:
    handler: handler.geoip
    layers:
      - arn:aws:lambda:us-west-2:377024778620:layer:geoip:2
    events:
      - http:
          path: geoip
          method: get
